name: continuous-integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        file: coverage.txt
        fail_ci_if_error: true
        verbose: true