name: continuous-integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.0'

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        file: coverage.txt
        fail_ci_if_error: true
        verbose: true
